'use client'
import { PostProvider } from 'context/NewsContext'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { useParams } from 'next/navigation'

import GlobalStyles from '../styles/global'
import ThemeProvider from './theme-provider'

const inter = Inter({ subsets: ['latin'] })

const metadata: Metadata = {
  title: 'Tribo News',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  const hat = useParams()

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <PostProvider hat={hat?.slug?.[1] as any}>
            <GlobalStyles />
            {children}
          </PostProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
