import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ThemeProvider from './theme-provider'
import GlobalStyles from '../styles/global'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Tribo News',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <GlobalStyles />
            {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
